name: Release Please And Docker
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: pyrroline-nest-server
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
